#!/usr/bin/env node
// Builds Towns.js, the Danish places the panel's town search looks in, from
// OpenStreetMap (© OpenStreetMap contributors, ODbL; see MAP-SOURCES.md). One
// query to the public Overpass API:
//
//   curl -fsS -A "omarchy-rain-radar-denmark-widget build" --data-urlencode \
//     'data=[out:json][timeout:120];area["ISO3166-1"="DK"][admin_level=2]->.dk;node[place~"^(city|town|village|suburb|quarter|hamlet)$"][name](area.dk);out body;' \
//     https://overpass-api.de/api/interpreter -o osm-places.json
//   node tools/build-towns.cjs osm-places.json > Towns.js
//
// GeoNames was tried first and dropped: it lacks real towns (Skærbæk in South
// Jutland, about 3,000 people) and has a population for few places. Places
// are ranked by OSM's population where tagged, else by kind (city, town,
// village, suburb, quarter, hamlet). The same name within 3 km is one place.
// Names that still occur more than once get the nearest city or town as a
// hint ("Skærbæk, near Tønder"). English names ("Copenhagen") are kept as an
// extra search key.
const fs = require("node:fs")
const path = require("node:path")
const MapModel = require(path.join(__dirname, "..", "MapModel.js"))

const RANK = { city: 0, town: 1, village: 2, suburb: 3, quarter: 4, hamlet: 5 }
const file = process.argv[2]
if (!file) { console.error("usage: node tools/build-towns.cjs osm-places.json > Towns.js"); process.exit(2) }

const km = (a, b) => Math.hypot((a.lat - b.lat) * 111.2, (a.lon - b.lon) * 111.2 * Math.cos(56 * Math.PI / 180))
const places = []
for (const e of JSON.parse(fs.readFileSync(file, "utf8")).elements) {
  const t = e.tags || {}
  if (!(t.place in RANK) || !t.name || !MapModel.contains(e.lat, e.lon)) continue
  const pop = parseInt(String(t.population || "").replace(/[^0-9]/g, ""), 10)
  places.push({ name: t.name, en: t["name:en"] && t["name:en"] !== t.name ? t["name:en"] : "", lat: e.lat, lon: e.lon,
    pop: isFinite(pop) ? pop : 0, rank: RANK[t.place] })
}

// most important first: population, then kind
const order = (a, b) => b.pop - a.pop || a.rank - b.rank || a.name.localeCompare(b.name, "da")
places.sort(order)
const kept = []
for (const p of places) if (!kept.some((q) => q.name === p.name && km(p, q) < 3)) kept.push(p)

const hubs = kept.filter((p) => p.rank <= 1)
const count = {}
for (const p of kept) count[p.name] = (count[p.name] || 0) + 1
for (const p of kept) {
  if (count[p.name] < 2) continue
  let best = null
  for (const h of hubs) if (h.name !== p.name && (!best || km(p, h) < km(p, best))) best = h
  if (best) p.near = best.name
}

const rows = kept.map((p) => JSON.stringify([p.name, Math.round(p.lat * 1e4) / 1e4, Math.round(p.lon * 1e4) / 1e4, p.pop, p.near || "", p.en]))
process.stdout.write(
  "// Generated by tools/build-towns.cjs from OpenStreetMap; do not edit.\n" +
  "// © OpenStreetMap contributors. This list is available under the Open Database License (ODbL),\n" +
  "// https://opendatacommons.org/licenses/odbl/ (see MAP-SOURCES.md).\n" +
  "// Danish places for the town search, most important first:\n" +
  "// [name, latitude, longitude, population (0 = not recorded), near (a hint for repeated names), English name]\n" +
  "var towns = [\n" + rows.join(",\n") + "\n]\n\n" +
  'if (typeof module !== "undefined") module.exports = { towns: towns }\n')
